const mongoose = require('mongoose')

// Case Study Schema
const caseSchema = new mongoose.Schema({
  caseId: {
    type: Number,
    required: true
  },
  client: {
    type: String,
    required: true
  },
  projectName: {
    type: String,
    required: true
  },
  year: {
    type: String,
    required: false
  },
  brand: {
    type: String,
    required: true
  },
  industry: {
    type: String,
    required: false
  },
  sector: {
    type: String,
    required: false
  },
  services: {
    type: String,
    required: false
  },
  projectType: {
    type: String,
    required: false
  },
  engagementType: {
    type: String,
    required: false
  },
  discipline: {
    type: String,
    required: false
  },
  technologies: {
    type: String,
    required: false
  },
  keywordLookup: {
    type: String,
    required: false
  },
  challenges: {
    type: String,
    required: false
  },
  solution: {
    type: String,
    required: false
  },
  provenResults: {
    type: String,
    required: false
  },
  situation: {
    type: String,
    required: false
  },
  keywords: {
    type: String,
    required: false
  },
  summary: {
    type: String,
    required: false
  },
  outline: {
    type: String,
    required: false
  },
  team: {
    type: String,
    required: false
  },
  images: {
    type: Number,
    required: false
  }
})

const CaseStudies = module.exports = mongoose.model('CaseStudies', caseSchema)

const preloadedStudies = [
  {
    "caseId": 1,
    "client": "Abaxis",
    "projectName": "HL7 Interface Development",
    "year": 2015,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "Development",
    "projectType": "",
    "engagementType": "Software Development",
    "discipline": "Software, Test",
    "technologies": "",
    "keywordLookup": "HL7, Class II, EMR",
    "challenges": "Current analyzer capable of sending only ASTM data\n\nAdding HL7 data capability to existing analyzer with minimum system changes\n\nSimplifying implementation of HL7 solution for small medical centers with limited IT support\n\nMissing documentation and artifa",
    "solution": "Created HL7 plug-in for analyzer that enabled broader connectivity \n\nDesigned and developed a plug-in to enable and simplify installation of HL7 solution \n\nDocumented QMS process to ensure consistency moving forward",
    "provenResults": "Enabled analyzer to deliver data in HL7 format\n\nAble to deliver a customized configuration of HL7 solution to small medical center customers \n\nNow have artifacts and documentation that meet requirements for a Class II medical device",
    "situation": "Leading diagnostic medical device manufacturer must improve and expand their connectivity strategy for lab equipment. They need a solution to enable their existing blood chemistry analyzers to communicate via HL7 with EMRs/LIMs.",
    "keywords": "HL7, Class II, EMR",
    "summary": "Leading diagnostic medical device company needed a solution to enable existing devices to send HL7 data to EMRs.",
    "outline": "Medical Device Send HL7 data to EMRs",
    "team": "Matt Eisedrath, Peter Rudolph",
    "images": 0
  },
  {
    "caseId": 2,
    "client": "Abbott Diabetes",
    "projectName": "Next Generation Hospital Glucose Meter and Data Management System",
    "year": "(Pre 2009)",
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "Project Management, Requirements Definition, Design, Development, Verification",
    "projectType": "Embedded",
    "engagementType": "",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "HL7, Class II, EMR, HIS",
    "challenges": "Diverse stakeholders accustomed to working in silo fashion (many from an acquired company)\n\nNo internal HL7 or enterprise platform experience\n\nVery tight time-to-market window (12 months)",
    "solution": "Provided dedicated team with deep domain and regulated development experience\n\nFull project responsibility: project management, requirements, architecture, design, development, and verification\n\nCollaborated with stakeholders to align technical decisions",
    "provenResults": "Class II data management system designed to receive data from a point-of-care device\n\nDesigned and implemented HL7 interfaces for the HIS and EMR enabling connectivity with meter while minimizing labor and data collection procedures\n\nMet aggressive market",
    "situation": "A manufacturer of hospital-based diabetes blood glucose monitors and meters needed to make significant updates to their hospital-based meters and develop a new data management system. Company facing an aggressive market window and had limited experience i",
    "keywords": "HL7, Class II, HIS, EMR",
    "summary": "Manufacturer of hospital-based diabetes blood glucose monitors and glucose meters needed update to hospital-based meters and new data management system. Foliage developed Class II data management system designed to receive data from a point-of-care device",
    "outline": "Developed Class II data management system",
    "team": "Greg Walsh, John Carey",
    "images": 0
  },
  {
    "caseId": 3,
    "client": "Abbott Molecular",
    "projectName": "Platform Upgrade & Migration",
    "year": 2015,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "HIT",
    "services": "Project Management, Development, Test",
    "projectType": "Enterprise",
    "engagementType": "Software Development",
    "discipline": "Software",
    "technologies": "Enterprise",
    "keywordLookup": "Migration, Code, Platform, Upgrade, Windows XP, Windows 7",
    "challenges": "Need to certify that new OS is compatible with all pieces of their software platform\n\nMust maintain same operational efficiency for hundreds of customers while migrating to the new OS\n\nComplex assessment due to the reliance on third party software",
    "solution": "Assessment identified high-risk areas for porting and code requiring rewriting\n\nImplementation strategy focused on moving over a million lines of code to new OS\n\nEnsured compatibility of new OS with ~25 third party software applications",
    "provenResults": "New OS allows for enhancement to existing product and future models\n\nNew user interface is more flexible and provides additional reporting options\n\nUpgraded verification test suite ensures continued accuracy of results",
    "situation": "Provider of diagnostic testing instruments is faced with obsolescence of current operating system (OS). This critical upgrade is necessary to maintain historical support levels \u000band will provide a solid foundation for the development \u000bof future instrument",
    "keywords": "Migration, code, platform, upgrade, Windows XP, Windows 7",
    "summary": "Windows XP migration to Windows 8.1, creation of Windows 8.1 Embedded Image, Verification testing of the code",
    "outline": "Migration and Verification",
    "team": "Dave Widland, Kevin Petriel",
    "images": 0
  },
  {
    "caseId": 4,
    "client": "Advantest",
    "projectName": "Advanced Analytics for Error Detection During Chip Design",
    "year": 2016,
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "Semiconductor Equipment",
    "services": "Consulting",
    "projectType": "",
    "engagementType": "Product Consulting",
    "discipline": "Consulting, Analytics",
    "technologies": "",
    "keywordLookup": "Data Analytics, Semiconductor, ATE, Automated Test Equipment, Chip Design",
    "challenges": "Improvement of chip development cycle with semi-automatic evaluation of chip prototypes and structured exploration of test results\n\nInability to detect error patterns and draw conclusions about potential root causes in the preliminary chip design\n\nOptimiz",
    "solution": "Refined algorithmic approaches iteratively and implemented proof of concepts \n\nApplied agile development method using Extreme Programming\n\nDesigned and implemented algorithms supporting error detection, error localization, and operation optimization \n\nEva",
    "provenResults": "A novel approach to analysis of chip design test results that can detect errors and optimize operations\n\nDemonstrator application for analysis and optimization of chips\n\nClean documentation of results and design decisions\n\nNew application programming inte",
    "situation": "A leading semiconductor company is trying to prove that advanced analytics can be used during chip design and development to detect design errors and optimize chip operations to vastly \nshorten the design cycle.",
    "keywords": "Data analytics, Semiconductor, ATE, automated test equipment, chip design",
    "summary": "A leading semiconductor company is trying to prove that advanced analytics can be used during chip design and development to detect design errors and optimize chip operations to vastly shorten the design cycle.",
    "outine": "Optimize chip design cycle",
    "team": "Aamir Chaudhry and Scott Evans\nGerman Analytics Team – Rich Sanford",
    "images": 0
  },
  {
    "caseId": 5,
    "client": "AgaMatrix",
    "projectName": "Mobile Application for Diabetes Data Management",
    "year": 2011,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "HIT",
    "services": "Design, Development",
    "projectType": "Embedded, Data",
    "engagementType": "Software Development",
    "discipline": "",
    "technologies": "iOS",
    "keywordLookup": "iOS, ADA, UI, Software",
    "challenges": "Tight time-to-market with software needed in 90-day window\n\nSeveral competitors vying \u000bfor first-to-market position\n\nLack of mobile application development experience and limited resources",
    "solution": "Designed and developed fully functional iOS mobile application for new device\n\nIntegrated team worked seamlessly with client to hit 90-day market window\n\nDeveloped UI, core data model, and several critical features to power application",
    "provenResults": "Hit market window with new iOS application\n\nApplication launched at ADA meeting and received favorably by diabetes industry\n\nDelivered recommendations to improve client’s internal development process",
    "situation": "An early-stage glucometers and data management solutions company struggling to develop an iOS application. They are looking to differentiate in a crowded marketplace with a    single device enabling proactive disease management –    iPhone plug-in meter w",
    "keywords": "iOS, ADA. UI, software",
    "summary": "As a development partner Foliage helped to develop an important mobile data management system for diabetics managing this chronic disease.",
    "outline": "iOS mobile application managing diabetes",
    "team": "John Carey, Greg Walsh",
    "images": 0
  },
  {
    "caseId": 6,
    "client": "Amgen",
    "projectName": "Product Design History File and Requirements Remediation",
    "year": "",
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "ESS",
    "projectType": "Requirements Remediation",
    "engagementType": "System Development",
    "discipline": "EE, EM, Systems Test, Consulting",
    "technologies": "",
    "keywordLookup": "62304, Remediation, FDA, Process Gap Assessment",
    "challenges": "Understanding the gaps between current practices and best practices relating to IEC 62304 design history files\n\nUndocumented requirements described by comments in code and some design documentation\n\nPerforming and documenting new verification tests to sho",
    "solution": "Performed gap analysis between current practices and IEC 62304 best practices\n\nDiscovered and documented requirements from source code and document review\n\nGenerated and documented new verification tests\n\nTraced the tests to requirements and demonstrated",
    "provenResults": "Updated all requirements documents within the design history documents to comply with IEC 62304 \n\nFacilitated submission of requirements documentation to the FDA \n\nReported several defects discovered during code inspection \n\nUpdated the verification trace",
    "situation": "Due to changes in the regulatory environment, several commercial dermatological laser systems came to be regarded as medical devices. Manufacturer needs to reverse engineer the systems to achieve IEC 62304 compliance.",
    "keywords": "62304, remediation, FDA process gap assessment",
    "summary": "Due to changes in the regulatory environment, several commercial dermatological laser systems came to be regarded as medical devices.  Manufacturer needed to reverse engineer the devices to achieve IEC 62304 compliance.",
    "outline": "IEC 62304 compliance",
    "team": "Mark Hersey",
    "images": 0
  },
  {
    "caseId": 7,
    "client": "Applied Materials",
    "projectName": "Cost Reduction of Etch Tool",
    "year": "",
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "Semiconductor Equipment",
    "services": "ESS",
    "projectType": "Value Engineering",
    "engagementType": "System Development",
    "discipline": "",
    "technologies": "Finite Element Analysis",
    "keywordLookup": "AMAT, Cost Reduction, Etch Tool, AC Box",
    "challenges": "Reduce product costs within 6 months to quickly impact bottom line \n\nDocumentation for chamber cooling manifold unavailable as it was owned by the supplier \n\nEnsure changes to the unit do not compromise performance of etch tool\n\nInternal engineering resou",
    "solution": "Reverse engineered existing unit and identified high-cost components for replacement or redesign\n\nSelected alternate commercial off-the-shelf components based on cost, functional and material compatibility analysis\n\nPerformed finite element analysis and p",
    "provenResults": "Reduced bill of materials cost by 32%\n\nOverall product cost reduced by 40% – double the original target of 20%\n\nCompetitive bidding identified new manufacturing partner and second source option\n\nRedesign and elimination of manufactured parts reduced assem",
    "situation": "Global company developing high precision manufacturing equipment for the semiconductor industry must meet corporate goal to reduce product costs by 20%. Chamber cooling manifold identified as individual subcomponent for significant cost reduction.",
    "keywords": "AMAT, cost reduction, etch tool, AC box",
    "summary": "Global company developing high precision manufacturing equipment for the semiconductor industry must meet corporate goal to reduce product costs by 20%. Chamber cooling manifold identified as individual subcomponent for significant cost reduction.",
    "team": "Myron Pugh, Lee Plovnick, Chuck Shafer",
    "outline": "Reduce product costs by 20%",
    "images": 0
  },
  {
    "caseId": 8,
    "client": "Arkray",
    "projectName": "Cloud-based Diabetes Management System",
    "year": 2015,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "HIT",
    "services": "Software Development",
    "projectType": "",
    "engagementType": "Software Development",
    "discipline": "Software",
    "technologies": "",
    "keywordLookup": "Diabetes, Cloud, Enterprise, Cybersecurity",
    "challenges": "Develop a new secure, easy-to-use cloud-based diabetes management system\n\nNew software must be developed to IEC 62304 standards and latest FDA cybersecurity guidance\n\nBalancing ease of use for patients while meeting current FDA cybersecurity guidance",
    "solution": "Performed cybersecurity risk assessment and identified security model to address security risks\n\nCreated a new secure cloud-based solution with a straightforward user interface\n\nDeveloped service oriented architecture based on the latest Microsoft technol",
    "provenResults": "Cybersecurity assessment model quantified risks and enabled appropriate security controls that complied with FDA cybersecurity guidance\n\nNew cloud-based solution improved usability for patients  and providers\n\nEncryption technology secured only sensitive",
    "situation": "A patient-centric diabetes product company looking to develop  a secure cloud-based diabetes management system. Existing system was outdated, challenging for patients to use and didn’t meet latest FDA cybersecurity guidance.",
    "keywords": "Diabetes, cloud, enterprise, cybersecurity",
    "summary": "A patient-centric diabetes products company looking to develop a secure cloud-based diabetes management system. Existing system was outdated, challenging for patients to use and didn’t meet latest FDA cybersecurity guidance.",
    "outline": "outline",
    "team": "Adam Hesse",
    "images": 0
  },
  {
    "caseId": 9,
    "client": "BioSignal",
    "projectName": "Application Migration to the Cloud",
    "year": 2014,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "HIT",
    "services": "",
    "projectType": "",
    "engagementType": "Software Development",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "Migration, Cloud, Enterprise, Biology, Neurology",
    "challenges": "Create a highly scalable and multi-tenancy solution\n\nModify existing data model to support multiple users with different security requirements\n\nAn unmodifiable third party desktop application at the core of the prototype needed to be deployed in the cloud",
    "solution": "Integrated application remoting technology to seamlessly operate the third party desktop application from a browser\n\nRefactored prototype source code enabling future scalability\n\nIntroduced access token system to improve user experience while ensuring the",
    "provenResults": "Client delivered to market a new cloud-based web admin portal serving multiple tenants in less than 6 months\n\nCreated all design history documents and facilitated FDA documentation submissions\n\nBusiness now well positioned to attract future funding and po",
    "situation": "An early stage company in the traumatic brain injury market looking to migrate a prototype single tenant web application to a scalable cloud infrastructure in less than 6 months.",
    "keywords": "Biology, cloud, migration, neurology, enterprise",
    "summary": "Migration strategy to merge multiple disparate HIS software systems to a new architecture",
    "outline": "outline",
    "team": "Adam Hesse, John, Carey, Greg Walsh",
    "images": 0
  },
  {
    "caseId": 10,
    "client": "Bruker",
    "projectName": "Bacterial Analysis & Microorganism ID System",
    "year": "",
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "Consulting, Development, Verification",
    "projectType": "",
    "engagementType": "System Development",
    "discipline": "Consulting, Software, Systems",
    "technologies": "",
    "keywordLookup": "LIM, Connectivity, Lab & Test, Workflow Management",
    "challenges": "Lack of technical know-how with complex system connectivity\n\nNeed additive system capability by expanding the technology\n\nTime-sensitive modification using the protocols native  to each device",
    "solution": "Identified alternatives and provided an analysis of build vs. buy\n\nProject management and quality assurance teams collaborated with client stakeholders to deliver expected results\n\nDeveloped and verified new connectivity solution",
    "provenResults": "New middleware solution allowed strong connectivity between two devices\n\nIncreased overall robustness, quality control, and user certainty\n\nClear tactical plan solved connectivity issues \n\nIncreased revenue in 4 months",
    "situation": "Biotechnology division of a global R&D company must address connectivity limitations with current ID system in order to expand market share. The solution must enable two devices   to exchange necessary worklists and results.",
    "keywords": "LIM, connectivity, lab & test, workflow management",
    "summary": "Biotechnology division of a global R&D company must address connectivity limitations with current ID system in order to expand market share. The solution must enable two devices   to exchange necessary worklists and results.",
    "outline": "outline",
    "team": "Tim Bosch, Madeline Shattow",
    "images": 0
  },
  {
    "caseId": 11,
    "client": "Cepheid",
    "projectName": "Diagnositc Device Cloud Solution",
    "year": 2014,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "HIT",
    "services": "Process Consulting",
    "projectType": "Embedded",
    "engagementType": "System Development",
    "discipline": "Systems",
    "technologies": "",
    "keywordLookup": "EMR, Cloud, Cybersecurity, Connectivity, LIS, IoT",
    "challenges": "Effectively manage and minimize support costs associated with increasing product distribution in emerging markets \n\nDelivery of software upgrades and loss prevention of IP or tampering that could impact the performance of the device\n\nAbility to remotely a",
    "solution": "Developed delivery system to push software updates via a cloud-based solution eliminating costly and time consuming process of shipping CDs\n\nNew rigorous security model addressed regional data requirements including package encryption and signing, verbose",
    "provenResults": "New cloud-based solution achieved $800,000 in annual savings over former costly manual process\n\nSoftware updates now being delivered quickly and securely without risk to the device\n\nNew architecture solution provides a solid framework to address current a",
    "situation": "Manufacturer of molecular diagnostic instruments under pressure from customers to simplify and secure the software update process for an existing device. The current product required manual updates (via CD) and did not allow for remote support. Need to dr",
    "keywords": "Cloud, cybersecurity, connectivity, LIS, EMR, IOT",
    "summary": "A leading molecular diagnostic company selected Foliage to develop a migration strategy and roadmap for moving their solution to the cloud.  The architecture leveraged cloud based platforms from BaaS providers in order to move software applications, remot",
    "outline": "outline",
    "team": "Norm Haas, Dan O'Connor, Adam Hesse",
    "images": 0
  },
  {
    "caseId": 12,
    "client": "Covidien (Mallinckrodt)",
    "projectName": "Contrast Injector System Development",
    "year": 2013,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "Requirements Definition, Design, Development",
    "projectType": "Systems, Control",
    "engagementType": "Software Development",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "Software, Product Costs, Development, Electrical, Mechanical",
    "challenges": "Internal development resources stretched thin and lack of recent experience leading product development efforts\n\nCost considerations factored into development strategy – either develop from scratch or modify existing product\n\nExisting product required sig",
    "solution": "Created and drove development strategy well-aligned with business objectives and market needs\n\nFull project responsibility for system development - software, electrical,  and mechanical\n\nManaged high-performance teams ensuring strong communication among a",
    "provenResults": "Well positioned to deliver the product to market within desired market window\n\nHigh quality product delivered with significantly improved software and product reliability\n\nHit initial target costs and completed follow-on Value Engineering engagement to lo",
    "situation": "A global healthcare medical device company must develop a contrast injection system for emerging markets. This next generation device requires more streamlined processes and must be easier to operate.",
    "keywords": "product costs, development, software, electrical, mechanical",
    "summary": "Developed complete contrast agent injector for the medical market including system design, mechanical system, electronic controls and software",
    "outline": "outline",
    "team": "John Carey, Chris Miles",
    "images": 0
  },
  {
    "caseId": 13,
    "client": "Drew Scientific",
    "projectName": "Whole Blood HbA1c Analyzer",
    "year": 2011,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "Design, Development",
    "projectType": "Embedded",
    "engagementType": "Software Development",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "SOM, Touchscreen, Fluidics, Ion-exchange, Chromatography, 3 Axis Stepper, Driven Sample, Loading Automation",
    "challenges": "Meet aggressive cost reduction targets to achieve desired product margins – reduce manufacturing costs by a third\n\nIdentify high-cost components for replacement without sacrificing product integrity\n\nImprove precision of fluidics path to enhance overall i",
    "solution": "Achieved significant cost  reductions by employing design for manufacturability methods that minimize part count and simplify assembly\n\nSystem redesign including electro-mechanical and control software optimized and reduced fluidics path\n\nImplemented new",
    "provenResults": "Met aggressive cost targets- reduced production costs by ~50%\n\nNew valve and pump component recommendations improved fluidics accuracy and met NGSP certification guidelines\n\nNew lower cost instrument improves manufacturer’s ability to compete in emerging",
    "situation": "Analytical device manufacturer looking to provide an upgrade in performance and accuracy for existing customers in emerging markets, at less than half the cost of competing devices. Key focus is on reducing product development costs while improving perfor",
    "keywords": "SOM,   touchscreen LCD,   \nfluidics, low cost ion-exchange chromatography\n3 axis stepper driven sample loading automation",
    "summary": "Developed prototype HbA1c analyzer product including electro-mechanical and control software.",
    "outline": "outline",
    "team": "John Carey, Dave Warburton",
    "images": 0
  },
  {
    "caseId": 14,
    "client": "Evoke",
    "projectName": "Web-based Portal for Wireless Wearable Sensor",
    "year": 2012,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "HIT",
    "services": "",
    "projectType": "",
    "engagementType": "Software Development",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "Data Analytics, Software, Connectivity, Scalability",
    "challenges": "Lack of technical resources and expertise developing web-based applications\n\nTransition from a product-based business model to new service-based business model\n\nAutomate a manual reporting and invoicing process to free up valuable technical resources and",
    "solution": "Experienced team led collaborative approach to design, development, and delivery of admin and client web-based portal\n\nRecommended underlying technology platforms to support scalable service-based business model\n\nCreated automated reporting process improv",
    "provenResults": "Collaborative approach introduced best practices to ensure the efficient use of \u000bin-house resources during development projects\n\nScalable software architecture provided solid framework for future development initiatives\n\nAchieved 80-90% time savings with",
    "situation": "A start-up neuroscience company with a wireless device for health monitoring seeking new service-based business model for their innovative approach to controlling data quality in diagnosis reporting. Primary objectives for the solution included developing",
    "keywords": "data, connectivity, software, scalability",
    "summary": "A start-up neuroscience company with a wireless device for health monitoring seeking new service-based\nbusiness model for their innovative approach to controlling data quality in diagnosis reporting.\nPrimary objectives for the solution included developing",
    "outline": "outline",
    "team": "Matt Eisedrath",
    "images": 0
  },
  {
    "caseId": 15,
    "client": "Evoke",
    "projectName": "Portable ECG Monitor",
    "year": "",
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "Design, Test, Verification",
    "projectType": "",
    "engagementType": "System Development",
    "discipline": "EE, Software, Systems, Systems Test, Test",
    "technologies": "",
    "keywordLookup": "Data Analytics, Portable EEG System, HRV, ECG",
    "challenges": "Scope and scale of product requires complex system expertise\n\nPortable system must manage, upload, and analyze vast amounts of data from remote sources\n\nSystem must be portable and run on battery power for extended periods of time",
    "solution": "Developed multiple prototypes to help refine portable device design \n\nCreated custom display for the processing of EEG data\n\nDesigned custom lithium ion battery to allow up to 8 hours of continuous use",
    "provenResults": "Product demo realized in six months and commercialization  in ten months\n\nDelivered full documentation of development process, source code, executable code, and images\n\nProvided roadmap to drive long-term product vision",
    "situation": "Start-up company wants to develop a new portable EEG system for brain assessment in the field. They need support to take them from concept to product commercialization in a very short period of time.",
    "keywords": "Portable EEG System, data analytics, Heart Rate Variability (HRV) and Electrocardiography (ECG)",
    "summary": "Start-up company wants to develop a new portable EEG system for brain assessment in the field. They need support to take them from concept to product commercialization in a short period of time.",
    "outline": "outline",
    "team": "John Carey, Dave Meyers",
    "images": 0
  },
  {
    "caseId": 16,
    "client": "FEI",
    "projectName": "High Performance Measurement System (Dual beam SEM)",
    "year": "",
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "Inspection/Test/Measurement",
    "services": "Consulting",
    "projectType": "Embedded",
    "engagementType": "Product Consulting",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "Semiconductor, Software, Dual Beam SEM, Architecture Assement",
    "challenges": "High configurability of current system compounding new development projects \n\nLegacy software built on older technologies and prone to breaking with any update\n\nLegacy architecture principles favor flexibility over reliability \n\nComplete rewrite of massiv",
    "solution": "Formulated new architecture focused on high reliability to address needs of semiconductor manufacturing market \n\nCurrent components assessed for reuse to achieve cost savings\n\nMigration strategy developed to incrementally bring up the new architecture qui",
    "provenResults": "Increased development velocity with improved process knowledge and technical experience with new technologies\n\nNew architecture represents a dramatic simplification that supports high reliability\n\nArchitectural design introduced real-time control and pred",
    "situation": "Leading global provider of measurement systems looking to increase market share in semiconductor equipment market faced customer pressures to enhance product features. Current product suffering debilitating reliability issues each time new features are ad",
    "keywords": "Dual beam SEM, architecture assessment, semiconductor, Software Reliability",
    "summary": "Leading global provider of measurement systems looking to increase market share  in semiconductor equipment market faced customer pressures to enhance product features. Current product suffering debilitating reliability issues each time new features are a",
    "outline": "outline",
    "team": "Dan O'Connor, Scott Evans",
    "images": 0
  },
  {
    "caseId": 17,
    "client": "Gerber",
    "projectName": "Next Generation Textile Cutter Control System",
    "year": 2010,
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "Discrete Manufacturing",
    "services": "Consulting, Design, Development, Test",
    "projectType": "Embedded, Controls",
    "engagementType": "System Development",
    "discipline": "Hardware and Software",
    "technologies": "C#, Windows CE",
    "keywordLookup": "Migration, Control System, Motion Control, Product Line, Acquisition",
    "challenges": "Multiple acquisitions resulted in the need to support several architectures – driving up R&D costs\n\nAging software and outdated technology creating reliability issues significantly delaying release of new features\n\nMust respond quickly to lower-priced, mo",
    "solution": "Assessed three architectures and identified components for reuse – reducing cost of the development effort\n\nDesigned and developed new control system including electronics and software, sensors, UI, real-time digital network, imaging, printing, and interf",
    "provenResults": "New product line architecture developed in 16 months\n\nOne scalable, flexible platform architecture rolled out across multiple product lines\n\nFaster time to market for new features ‒ responding quicker to market demands\n\nEntry into new markets now possible",
    "situation": "Manufacturer of industrial cutting machines looking to develop next-generation textile cutter control system with scalable architecture to enable faster delivery of new product enhancements. Development efforts constrained by complications arising from mu",
    "keywords": "Control system, motion control, migration, product line, acquisition, architecture",
    "summary": "Manufacturer of industrial cutting machines looking to develop next generation textile cutter control system with scalable architecture to enable faster delivery of new product enhancements. Development efforts constrained by complications arising from mu",
    "outline": "outline",
    "team": "Tom Mariano\nRick Flanders\nScott Evans",
    "images": 0
  },
  {
    "caseId": 18,
    "client": "GSI (Now ESI)",
    "projectName": "Laser Marking Control System",
    "year": "",
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "Discrete Manufacturing",
    "services": "Consulting, Design, Product Development",
    "projectType": "Embedded, Controls",
    "engagementType": "Software Development",
    "discipline": "Software, Systems",
    "technologies": "",
    "keywordLookup": "Migration, Architecture Strategy, VDA, Manufacturing, Off-Shore, On-Shore",
    "challenges": "Software architecture could no longer support adding new features without negatively affecting system performance\n\nEnhanced automation capabilities significantly decreased tool throughput\n\nLegacy architecture and design limitations preventing new enhancem",
    "solution": "Value-Driven Analysis captured and verified critical system requirements based on business and technical goals of the system\n\nEvaluation of existing code identified several components for reuse in new architecture\n\nLed development of new architecture stra",
    "provenResults": "Three-week strategic plan provided short-term solution to enhance system performance and meet market demand\n\nLong term architecture and cost-effective migration plan to move existing product line onto a platform that could support future development\n\nFlex",
    "situation": "Global leader in laser precision technology developing next generation laser marker control system with architecture that can support product enhancements and new technologies. Urgent need to improve performance to sustain market position while developing",
    "keywords": "architecture strategy, VDA, migration, manufacturing, off-shore, on-shore",
    "summary": "Global leader in laser precision technology developing next generation laser marker control system with architecture that can support product enhancements and new technologies. Urgent need to improve performance to sustain market position while developing",
    "outline": "outline",
    "team": "Tim Bowe, Karl Aeder",
    "images": 0
  },
  {
    "caseId": 19,
    "client": "Harvest Automation",
    "projectName": "Fleet Management System for Autonomous Material Handling",
    "year": 2015,
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "AMH",
    "services": "Product Development",
    "projectType": "",
    "engagementType": "",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "Fleet Control Management, Robotics, Retail Distribution, Time to Market",
    "challenges": "Extremely tight deadline   to have operating demo ready – 8 weeks\n\nUpgrading current fleet control management system to now operate  with multiple robots \n\nIdentified gaps in bandwidth and expertise in specific areas criticalto project execution",
    "solution": "Collaborated with business and technical leadership to define development plan that leveraged existing autonomous robot technology\n\nLed integrated team in software development effort \n\nDesigned and developed new fleet control management system",
    "provenResults": "New demo-ready solution delivered on time and within budget\n\nWell positioned to enter the retail distribution and fulfillment market with new solution\n\nImproved development processes and best practices will enable product extensibility and acceleration of",
    "situation": "A material handling company focused on robotics looking to enter the e-commerce retail distribution and fulfillment arena with a solution to improve efficiency and productivity in thepick-to-order space. Company looking for assistance to leverage existing",
    "keywords": "Fleet Control Management, Robotics, Retail distribution, time to market",
    "summary": "A material handling company focused on robotics looking to enter the e-commerce retail distribution and fulfillment arena with a solution to improve efficiency and productivity in the pick-to-order space. Company looking for assistance to leverage existin",
    "outline": "outline",
    "team": "Aamir Chaudhry",
    "images": 0
  },
  {
    "caseId": 20,
    "client": "Heartware",
    "projectName": "LVAD Controller and Monitor",
    "year": 2012,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "Requirements Definition, Design, Development",
    "projectType": "Control",
    "engagementType": "Process Consulting",
    "discipline": "Systems Test",
    "technologies": "",
    "keywordLookup": "Control System, Next-Generation Device, LVAD, Implantable, Test processes",
    "challenges": "To remain competitive,must release a product to U.S. market quickly\n\nAvailability of key staff to focus on commercialization efforts is limited due to clinical trial work\n\nLack of systems knowledge with Class III medical devices",
    "solution": "Established a phased development plan to ensure product release within 18-month window\n\nSystems engineering support met product launch time frame\n\nReduced regulatory risk by identifying verification and validation criteria",
    "provenResults": "Achieved commercialization of product in 17 months\n\nProduct received FDA Class III approval\n\nEstablished processes and procedures for future regulated product development",
    "situation": "LVAD device manufacturer that is CE approved and sold in Europe wants to enter the U.S. market. Device needs Class III approval and they are up against a tight 18-month plan to commercialize the product.",
    "keywords": "Control software, test processes, next-generation device, LVAD, implantable",
    "summary": "LVAD device manufacturer that is CE approved and sold in Europe wants to enter the U.S. market. Device needs Class III approval and they are up against a tight 18-month plan to commercialize the product.",
    "outline": "outline",
    "team": "John Carey, Matt Eisendrath, John Montrone, Alan Walsh, Peter Ferguson",
    "images": 0
  },
  {
    "caseId": 21,
    "client": "Intelligrated",
    "projectName": "Warehouse Control System Architecture",
    "year": "",
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "AMH",
    "services": "Consulting",
    "projectType": "",
    "engagementType": "System Development",
    "discipline": "Consulting, Software, System Architecture",
    "technologies": "",
    "keywordLookup": "IoT, Warehouse Automation, Assessment, Architecture Definition",
    "challenges": "Next-generation system architecture was undocumented\n\nDevelopment of system had started, and was accumulating technical debt\n\nPartial product knowledge distributed across multiple divisions\n\nArchitecture needs to be extensible to Cloud and future IoT tech",
    "solution": "Architecture assessment identified key gaps, risks, and technical debt\n\nDesigned and documented a multi-tiered service oriented architecture to address a myriad of use cases and support future growth\n\nComprehensive project plan and estimate enabled priori",
    "provenResults": "Architecture recommendations and system plans executed immediately\n\nDramatically reduced time to configure new warehouse system from months to weeks\n\nFuture plans to develop a comprehensive integration, test, and simulation strategy identified",
    "situation": "Due to a shift in the marketplace driven by e-commerce and omni-channel demand, the manufacturer of automated warehouse solutions must deliver a next-generation system with real-time adaptive workflows to optimize fulfillment operations. A highly configur",
    "keywords": "Assessment, Architecture Definition, Warehouse Automation, IoT",
    "summary": "Due to a shift in the marketplace driven by e-commerce and omni-channel demand, the manufacturer of automated warehouse solutions must deliver a next-generation system with real-time adaptive workflows to optimize fulfillment operations. A highly configur",
    "outline": "outline",
    "team": "Amit Shah, Scott Evans",
    "images": 0
  },
  {
    "caseId": 22,
    "client": "Keurig",
    "projectName": "Consumer Device IoT Platform",
    "year": 2015,
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "Consumer Electronics",
    "services": "IoT, Design, Development",
    "projectType": "",
    "engagementType": "System Development",
    "discipline": "EE, Software, Systems",
    "technologies": "",
    "keywordLookup": "Software, IoT, Wireless, Embedded, Systems",
    "challenges": "Identifying multiple connectivity, user interfaces, data transfer, capabilities, and scenarios to add to their product\n\nDetermining the most beneficial IoT capabilities to build into the product\n\nTesting a wide variety of customer use cases",
    "solution": "Designed and built a new test platform in four months \n\nSystem included multiple connectivity options, user interface methods, and data storage options\n\nCustomized various use cases to set up specific trials for consumer testing",
    "provenResults": "Able to identify the most compelling IoT use cases with    new test platform\n\nExpanded use cases to gain detailed insights for specific product features \n\nGained an understanding of how to productize IoT features",
    "situation": "Manufacturer of beverage brewing systems facing intense pressure to add features and functionality that leverage the IoT. Need help identifying the most compelling features and functionality to appeal to new and existing customers.",
    "keywords": "IoT, Wireless, EE, Systems, Software, Embedded,",
    "summary": "Manufacturer of beverage brewing systems facing intense pressure to add features and functionality that leverage the IoT. Need help identifying the most compelling features and functionality to appeal to new and existing customers",
    "outline": "outline",
    "team": "Tom Mariano",
    "images": 0
  },
  {
    "caseId": 23,
    "client": "KLA - Tencor",
    "projectName": "Improved Data Handling Solution for Metrology",
    "year": 2015,
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "Semiconductor Equipment",
    "services": "Project Management, Design, Development, Test",
    "projectType": "Data",
    "engagementType": "Software Development",
    "discipline": "Software, Test",
    "technologies": "MongoDB",
    "keywordLookup": "Big Data",
    "challenges": "Equipment and metrology analysis software solution at risk due to increased competition\n\nCurrent data handling solution based on old technology unable to process massive amounts of data\n\nLimited resources available to quickly deliver improved solution wit",
    "solution": "Proposed architecture incorporating new Big Data technology to enable parallel processing of large amounts of data\n\nRedesigned database layer and recommended new technology to improve data access times\n\nManaged design, development and testing of improved",
    "provenResults": "System throughput improved by 10X – leapfrogging the competition\n\nNew data handling solution with scalability and performance enhancements completed 6 months ahead of schedule\n\nWell-positioned to deliver new solution to market – improving competitive adva",
    "situation": "A global provider of process measurement and control, yield management and data analysis solutions for semiconductor manufacturing faced with making major improvements to an existing product. Customer requests driving enhancements to the capabilities and",
    "keywords": "Big Data",
    "summary": "A global provider of process measurement and control, yield management and data analysis solutions for semiconductor manufacturing faced with making major improvements to an existing product. Customer requests driving enhancements to the capabilities and",
    "outline": "outline",
    "team": "Norm Haas",
    "images": 0
  },
  {
    "caseId": 24,
    "client": "L-3 Communications Security Detection",
    "projectName": "High-energy X-ray Large Cargo Screening System",
    "year": 2012,
    "brand": "Foliage",
    "industry": "Aerospace & Defense",
    "sector": "Government Systems",
    "services": "Requirements Definition, Design, Development",
    "projectType": "Control",
    "engagementType": "Software Development",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "X-Ray, Scanning System, Security, Mobile",
    "challenges": "Each cargo scanner creates different image formats\n\nDiffering analysis tools requires specialized personnel and training requirements\n\nLimited opportunity to interchange personnel when needed",
    "solution": "Developed a secure network environment connecting all X-ray scanners to a common datacenter\n\nCreated a front-end for each scanner with a subsystem to convert images to a common format\n\nUpgraded selected image analysis application suite to manage all   X-r",
    "provenResults": "Image analysts utilize a single application suite\n\nKey personnel now able to work together in a central location, increasing effectiveness\n\nEstablished Best-in-Class features that are now the key criteria in X-ray scanner selection",
    "situation": "A well-established international shipping port currently utilizing cargo scanners from several different manufacturers must reduce costs. By centralizing operations and utilizing a single effective image analysis application suite with existing scanners,",
    "keywords": "x-ray, scanning system, security, mobile",
    "summary": "Developed control software and hardware for a high-energy X-ray scanning system for large cargo containers. The full system was designed to be a fully mobile system",
    "outline": "outline",
    "team": "Jay Gray, David Martin",
    "images": 0
  },
  {
    "caseId": 25,
    "client": "McKesson",
    "projectName": "Advanced Population Health Solution",
    "year": 2014,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "HIT",
    "services": "Consulting",
    "projectType": "Architecture, Big Data, Analytics, Platform Strategy",
    "engagementType": "Product Consulting",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "Platform, Big Data, Analytics",
    "challenges": "Multiple applications with redundant capabilities across business units \n\nBusiness units are siloed creating operational inefficiencies\n\nEach application has a unique approach to data acquisition and storage from a common data set",
    "solution": "Developed a centralized platform to support common capabilities required by various business units\n\nDeveloped a common data management platform that leverages cloud and big data technologies\n\nCreated customizable architecture to address the unique needs o",
    "provenResults": "Defined architectural approach to create a common data management platform\n\nCreated cost, risk, and competency assessment models, providing visibility to executive management to inform decision making\n\nWell positioned to deliver a comprehensive product su",
    "situation": "Fortune 100 healthcare company needs to develop an advanced population health solution to address the market’s value-based reimbursement structure. Current population health market is highly fragmented, without a dominant product suite.",
    "keywords": "Big Data, analytics, platform strategy",
    "summary": "Fortune 100 healthcare company needs to develop an advanced population health solution to address the market’s value-based reimbursement structure. Existing population health market        is highly fragmented, without a dominate product suite.",
    "outline": "outline",
    "team": "Tim Bosch, Matt Eisendrath",
    "images": 0
  },
  {
    "caseId": 26,
    "client": "McKesson",
    "projectName": "Data Management System Architecture",
    "year": 2015,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "HIT",
    "services": "Consulting, Design, Development, Test, Verification",
    "projectType": "",
    "engagementType": "Systems Development, Process Consulting",
    "discipline": "Consulting",
    "technologies": "",
    "keywordLookup": "Roadmap, Security, Data Management, Architecture Platform",
    "challenges": "Undocumented current architecture\n\nDisparate handling requirements for different data sources\n\nEnhance security to protect patient and customer data\n\nConstruct metadata and data access mechanisms to support advanced analytics and specific security needs",
    "solution": "Documented the current architecture and defined new secure solution for data management\n\nDeveloped rules-based data handling solution for disparate sources\n\nCreated roadmap to migrate current capabilities to new system  \n\nDefined tools and new processes t",
    "provenResults": "Created complete documentation of current architecture\n\nDesigned and verified new data management approach and data access mechanisms\n\nNew robust architecture to support evolving business models and meet market needs",
    "situation": "Provider of pharmacy services needs to significantly expand patient data management and analytics capabilities. The current solution and technology are insufficient to meet increasing  data volumes, data sources, number of    customers, and analytics need",
    "keywords": "Data Management, Roadmap, Security, Architecture, Platform",
    "summary": "Provider of pharmacy services needs to significantly expand patient data management and analytic capabilities. The current solution and technology are insufficient to meet increasing  data volumes, data sources, number of customer and      analytic needs.",
    "outline": "outline",
    "team": "Tim Bosch, Matt Eisendrath",
    "images": 0
  },
  {
    "caseId": 27,
    "client": "Medtronic - Navigation",
    "projectName": "Intra-operative Surgical Imaging System",
    "year": 2009,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "Consulting, Requirements Definition, Design, Development",
    "projectType": "",
    "engagementType": "Product Consulting",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "Software, Design",
    "challenges": "The acquired surgical imaging system lacked key artifacts such as system architecture documentation\n\nAssessment findings needed quickly to incorporate into next product release\n\nFuture product enhancements were at a stand-still pending the resolution of r",
    "solution": "Performed full software and product architecture assessment in less than 10 weeks\n\nAssessed testing approach and processes to determine how reliability issues had been missed prior to release\n\nImprovements recommended to address the gaps identified in des",
    "provenResults": "Implemented and tested refactored software control architecture solving reliability issues, improving system performance and resolving customer satisfaction challenges\n\nImproved architecture provided stronger foundation upon which to build new product fea",
    "situation": "Surgical imaging division of large, global medical device company needed to respond quickly to address product reliability issues voiced by customers. To isolate and stabilize these issues, a comprehensive product assessment was implemented.",
    "keywords": "software, design, architecture",
    "summary": "Assessed existing control software for an x-ray-based intrasurgical imaging system. Subsequently were engaged to provide a recommendation for a new software control architecture which would improve overall system reliability.",
    "outline": "outline",
    "team": "Tim Bowe, Dan O'Connor",
    "images": 0
  },
  {
    "caseId": 28,
    "client": "Novartis",
    "projectName": "Companion Diagnostic (CDx) Platform Strategy",
    "year": 2013,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "Consulting, Development",
    "projectType": "Class III, Product Platform, Architecture Strategy",
    "engagementType": "Software Development",
    "discipline": "Software",
    "technologies": "",
    "keywordLookup": "Architecture Strategy, Lab & Test, Drug Development, Product Platform",
    "challenges": "Relying on spreadsheets and email for data acquisition and analysis\n\nManual process is very time consuming and prone to human error\n\nHigh cost and shrinking timeline to develop individual companion diagnostics",
    "solution": "Software managed data acquisition and analysis \n\nCommon platform allows CDx algorithms to be developed, tested, and released without redevelopment of common capabilities\n\nAutomated key manual processes",
    "provenResults": "New platform streamlined and improved the data acquisition and analysis process\n\nAutomated process reduced analysis time and errors\n\nCommon platform now supports all drug trials",
    "situation": "Leading pharmaceutical company looking to automate the acquisition and analysis of clinical trial data. They need an approach that will help them streamline work processes to increase workflow efficiency and improve data quality and integrity.",
    "keywords": "product platform, architecture strategy, lab & test, drug development, metrics",
    "summary": "Leading pharmaceutical company looking to automate the acquisition and analysis of clinical trial data. They need an approach that will help them streamline work processes to increase workflow efficiency and improve data quality and integrity.",
    "outline": "outline",
    "team": "Tim Bosch",
    "images": 0
  },
  {
    "caseId": 29,
    "client": "PepsiCo",
    "projectName": "Universal Liquid Dispensing System",
    "year": 2013,
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "Discrete Manufacturing",
    "services": "Consulting, Design, Development, Test, Project Management",
    "projectType": "Hardware",
    "engagementType": "System Development",
    "discipline": "ME, Test",
    "technologies": "",
    "keywordLookup": "Manufacturing, Hardware, Beverage Filler Valve, Consumer Goods, Food and Beverage, Systems",
    "challenges": "Existing dispensing system optimized for speed, not liquid variability \n\nDispensing system requires complete stop and rework as fluid viscosity changes, impacting cost and efficiency\n\nCost-effective solution must address consistent pour and liquid variabi",
    "solution": "Systems thinking approach identified potential solutions leading to redesign of existing dispensing valve \n\nDesigned and built prototype for new dispensing valve \n\nNew valve design optimized for reliability, consistency, and efficiency",
    "provenResults": "Innovative universal dispensing valve capable of efficiently managing a range of fluid characteristics\n\nSolution delivered in less than six months ‒ patents on design pending\n\nFaster response to market trends now possible\n\nNew design provided new market p",
    "situation": "Beverage dispensing facilities must rapidly modify existing production process without downtime. Developing a universal liquid dispensing system to accurately dispense a range of fluid viscosities and inclusions at high speeds in a corrosive environment i",
    "keywords": "hardware, beverage filler valve, systems, manufacturing, consumer goods, food and beverage",
    "summary": "Beverage dispensing facilities must rapidly modify existing production process without down time. Developing a universal liquid dispensing system to accurately dispense a range of fluid viscosities and inclusions at high speeds in a corrosive environment",
    "outline": "outline",
    "team": "David Martin, Dave Warburton, Tom Evans",
    "images": 0
  },
  {
    "caseId": 30,
    "client": "Philips",
    "projectName": "Cloud-Based Portal for Mobile Imaging Device",
    "year": 2012,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "HIT",
    "services": "Software Development",
    "projectType": "",
    "engagementType": "Software Development",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "Cloud, Imaging, Mobile, Cloud Based Portal",
    "challenges": "Extreme competitive pressure to build a working, demonstrable solution in less than 90 days\n\nChallenged by availability of mobile and enterprise competencies\n\nBuild a foundational, scalable architecture while enabling connectivity to providers and externa",
    "solution": "Designed and developed cloud-based portal with connectivity to a mobile imaging device\n\nApplication of agile methodology led to rapid development of device\n\nDesigned and developed architecture and repository to capture data for advanced analytics",
    "provenResults": "Created end-to-end working prototype with GUI features integrated with functional backend logic and services providing connectivity to the cloud\n\nProject completion in 90 days allowed client to maintain competitive timelines\n\nIdentified opportunities for",
    "situation": "A global medical device manufacturer looking to differentiate by introducing a mobile imaging device for use outside of traditional healthcare facilities. Primary objective was to rapidly build a cloud-based portal allowing a mobile device \nto send images",
    "keywords": "Cloud, imaging, mobile, cloud-based portal,",
    "summary": "A global medical device manufacturer looking to differentiate by introducing a mobile imaging device for use outside of traditional healthcare facilities.  Primary objective was to rapidly build a cloud-based portal allowing a mobile device to send images",
    "outline": "outline",
    "team": "",
    "images": 0
  },
  {
    "caseId": 31,
    "client": "Sanmina SCI",
    "projectName": "Biopsy Imaging System",
    "year": 2014,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "ESS",
    "projectType": "Value Engineering",
    "engagementType": "",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "Imaging, Sanmina, Value Engineering, DFMA",
    "challenges": "Project stakeholders siloed due to an acquisition\n\nInferior product reputation in the marketplace\n\nLack of power system expertise in-house\n\nExperiencing thermal issues in device cabinet",
    "solution": "Performed DFMA on design leading to simplified assembly\n\nPerformed cost analysis on components resulting in design optimization\n\nRecommended distributed power approach to resolve thermal issues",
    "provenResults": "Achieved 32% cost reduction on components resulting in overall sustaining cost savings\n\nResolved thermal issues by redistributing power to the device\n\nROI achieved in 14 months",
    "situation": "A global medical device company needed to simplify assembly of its device to lower sustaining costs while solving  performance issues. Company reputation was at stake.",
    "keywords": "Sanmina, value engineering. Imaging, DFMA",
    "summary": "Biopsy Imaging system product cost too high with complex assembly and service processes, the service time drives low customer-perceived quality, and thermal issues inside cabinet.",
    "outline": "outline",
    "team": "Carl Blahut, Myron Pugh",
    "images": 0
  },
  {
    "caseId": 32,
    "client": "SET Corporation",
    "projectName": "Counter Bomber Surveillance System",
    "year": 2009,
    "brand": "Foliage",
    "industry": "Aerospace & Defense",
    "sector": "Government Systems",
    "services": "Development, Test",
    "projectType": "Commercial, ITAR Regulated, Windows CE, Python, Java, C++",
    "engagementType": "",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "Software, Development, Systems, Integration and Test",
    "challenges": "Development schedule behind by 6 months  \n\nInsufficient in-house capabilities with complex software and systems, development, integration and test",
    "solution": "Determined clear path forward based on assessment of the development status \n\nAssessment revealed that additional development was not required\n\nUtilized best practices in continuous integration and regression testing ensuring  product launch schedule  was",
    "provenResults": "Streamlined test and integration process\n\nReduced projected resource requirements, saving time and money\n\nRecovered schedule and launched product on time",
    "situation": "To secure investors for a second round of funding, DOD technology start-up must expedite the initial product launch. New product is a suicide bomber detection system that integrates sensors and software to automatically assess, at a safe distance, the thr",
    "keywords": "software and systems development, integration and test",
    "summary": "The client had a working prototype that was developed in a research environment. The system software was built and deployed by a collection of manual processes. There was no formal test plan or procedure to verify system operations.",
    "outline": "outline",
    "team": "",
    "images": 0
  },
  {
    "caseId": 33,
    "client": "SICK, Inc.",
    "projectName": "Enterprise Analytics Software for Logistics Management",
    "year": 2015,
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "AMH",
    "services": "Analytics",
    "projectType": "",
    "engagementType": "",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "Big Data, Logistics Management, Package Analytics, Sensors, Consulting",
    "challenges": "Needed package analytics software development support\n\nNew enterprise level software platform must manage multiple warehouses in real-time\n\nSoftware platform must align operational data from various sources to improve warehouse operations and productivity",
    "solution": "Created software requirements document\n\nDeveloped new visualization GUI to display reports, charts, and data \n\nProvided  business intelligence to improve efficiency and productivity utilizing advanced configuration management tools\n\nNew feature capabiliti",
    "provenResults": "New enterprise level software platform delivered on time\n\nReporting analysis web service – API (predictive analysis) allowing company to plan for likely events before they even happen\n\nNew features and enhancements allow data to be displayed with charts a",
    "situation": "A solution provider for logistics automation looking to differentiate themselves in a crowded marketplace must deliver an enterprise level software platform. New platform must bring large amounts of real-time data from facility to enterprise level to enab",
    "keywords": "Package Analytics, Big Data, Logistics Management, Sensors, Consulting",
    "summary": "A solution provider for logistics automation looking to differentiate themselves in a crowded marketplace must deliver an enterprise level software platform. New platform must bring large amounts of real-time data from facility to enterprise level to enab",
    "outline": "outline",
    "team": "Norb Gravelle, Roger Kerns,  Aamir Chaudhry",
    "images": 0
  },
  {
    "caseId": 34,
    "client": "Siemens",
    "projectName": "Predictive Maintenance Strategy and Implementation",
    "year": 2016,
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "Semiconductor Equipment",
    "services": "Consulting, Design, Development and Analytics",
    "projectType": "",
    "engagementType": "Analytics",
    "discipline": "Consulting and Analytics",
    "technologies": "",
    "keywordLookup": "Data Analytics, Analytics, Predictive Maintenance, Remote Diagnostics",
    "challenges": "No predictive analytics being used on collected data\n\nData mining environments overwhelmed by large data volume and unable to interpret data\n\nCurrent data handling solution cannot process massive amounts of data\n\nLimited resources and lack of available in",
    "solution": "Reviewed and improved the data infrastructure\nImplemented advanced data analytics, reporting, and integration\n\nCreated a full data preparation cycle which improved data quality\n\nPut predictive business rules into effect and added predictive modeling to th",
    "provenResults": "Effectively stabilized platform and overcame data quality issues\n\nProvided model templates to feed into a Model Factory\n\nDelivered models achieved necessary quality gates \n\nPredicted and prevented numerous egregious failures by implementing predictive mod",
    "situation": "Global capital equipment supplier dealing with high warranty and service costs for thousands of units running in the field. Predictive analytics could be a viable solution for driving costs down, but the current data handling solution is incapable of proc",
    "keywords": "Predictive maintenance, analytics, data, remote diagnostics",
    "summary": "Global capital equipment supplier dealing with high warranty and service costs for thousands of units running in the field. Predictive analytics could be a viable solution for driving costs down, but the current data handling solution is incapable of proc",
    "outline": "outline",
    "team": "German analytics team",
    "images": 0
  },
  {
    "caseId": 35,
    "client": "Stereotaxis",
    "projectName": "Multi-function Display for Surgical Navigation System",
    "year": "(Pre 2009)",
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "",
    "projectType": "",
    "engagementType": "Software Development",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "FDA, Robotics, Cardiac, Magnetic, Value Driven Analysis, Technology Strategy, Radiation",
    "challenges": "Commercialize the system including obtaining FDA approval\n\nExpand the technology into additional modalities, such as ultrasound\n\nLack of in-house resources to meet time-to-market goal of 9-12 months",
    "solution": "Working with management and in-house engineering teams, developed technology strategy and product roadmap \n\nVerified critical productrequirements using proprietary Value Driven Analysis tool\n\nReinforced client’s in-house capabilities with engineering and",
    "provenResults": "Product received FDA approval and was brought to market early\n\nDelivered scalable and supportable platform architecture enabling future capability enhancements and extensions\n\nEnhanced market acceptability for this highly innovative product",
    "situation": "Global manufacturer of robotics systems for the treatment of cardiac arrhythmias focused on developing a remote magnetic navigation system for cardiac catheterization. Additional requirement for new system is to reduce physicians' exposure to radiation du",
    "keywords": "robotics, cardiac, magnetic, radiation, FDA, value driven analysis, technology strategy",
    "summary": "Global manufacturer of robotics systems for the treatment of cardiac arrhythmias to develop a remote magnetic navigation system for cardiac catheterization, reducing physicians’ exposure to radiation during fluoroscopy procedures",
    "outline": "outline",
    "team": "",
    "images": 0
  },
  {
    "caseId": 36,
    "client": "SureWx",
    "projectName": "Migration to Cloud ASP",
    "year": 2014,
    "brand": "Foliage",
    "industry": "Aerospace & Defense",
    "sector": "Commerical Development",
    "services": "Consulting",
    "projectType": "Deicing, Weather, Airlines, Cloud, Fault Tolerant",
    "engagementType": "",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "",
    "challenges": "Tight time-to-market — needed a sufficient improvement on current solution to buy time to develop the new technology solution\n\nNew to cloud technology hampered by internal resistance to that approach",
    "solution": "Facilitated efforts from all key business and technical stakeholders\n\nProduced preliminary software architecture and high-level requirements for the new solution\n\nIntegrated team worked seamlessly with client to produce the deliverables in just three week",
    "provenResults": "Produced interim approach to satisfy immediate need for the upcoming season\n\nProduced vision, architecture and requirements to serve as foundation for the long-term solution",
    "situation": "A market-leading Aerospace company looking to develop product vision and technology roadmap for the next 5+ years. To dominate their time-driven product space, they must launch a cloud-based system that supports short, efficient integration solutions for",
    "keywords": "deicing, weather, airlines, cloud, fault tolerant",
    "summary": "Early corporate focus on the design , manufacturing and deployment of Weather Station Hardware. Business model switched to that of an Application Service Provider. Prototype application and hosting center both need major upgrade to support the planned rap",
    "outline": "outline",
    "team": "Ari Berman, Charlie Alfred, Michael Dixon",
    "images": 0
  },
  {
    "caseId": 37,
    "client": "Symbotic",
    "projectName": "System Mixed Pallet Building",
    "year": 2012,
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "AMH",
    "services": "Design, Development",
    "projectType": "Embedded",
    "engagementType": "System Development",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "",
    "challenges": "Customer demand driving urgency to deliver new solution within 6 months \n\nOff-the-shelf solutions did not meet specific custom requirements\n\nHighly available and scalable solution to be architected from the ground up",
    "solution": "Refined palletizing algorithms to generate an optimized solution\n\nTested palletizing algorithms in simulation to prove performance and efficiency measures\n\nProvided a highly experienced team to architect, design, develop, and test the new system",
    "provenResults": "New solution developed with no impact on surrounding systems\n\nHighly robust, scalable system improved palletization efficiency\n\nUpdated system architecture documentation enabling more efficient development of future system features and enhancements\n\nHit m",
    "situation": "An automated material handling solution provider needed to develop a new mixed pallet building system within a very tight market window. Solution must provide fast re-planning, greater efficiency and control while allowing for customization to meet future",
    "keywords": "",
    "summary": "An automated material handling solution provider developing a new mixed pallet building system within a very tight market window. Solution must provide fast re-planning, greater efficiency and control while allowing for customization to meet future busine",
    "outline": "outline",
    "team": "Tom Mariano, Jeff Liscouski",
    "images": 0
  },
  {
    "caseId": 38,
    "client": "Symbotic",
    "projectName": "Warehouse Automation & Control System",
    "year": 2013,
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "AMH",
    "services": "Consulting, Design, Development",
    "projectType": "",
    "engagementType": "System Development",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "WCS",
    "challenges": "Extremely tight time-to-market deadline of 9 months\n\nRealized gaps in bandwidth, experience and expertise in specific areas \n\nOrganization and development processes not structured to deliver effectively",
    "solution": "Recommended process changes to improve the software development lifecycle\n\nCollaborated with business and technical leaders to define product roadmap and software development plans \n\nManaged integrated team comprised of both onshore and offshore resources",
    "provenResults": "Met aggressive time-to-market goal with new warehouse automation solution\n\nDelivered highly configurable solution reducing customization for future installations\n\nNew innovative solution gave company strong competitive advantage in their market",
    "situation": "Company developing a new warehouse automation system faced aggressive time-to-market deadline to satisfy customer requirements. This solution would improve warehouse operational parameters such as storage density, inventory traceability and throughput cyc",
    "keywords": "WCS",
    "summary": "Company developing a new warehouse automation system faced aggressive time-to-market deadline to satisfy customer requirements. This solution would improve warehouse operational parameters such as storage density, inventory traceability and throughput cyc",
    "outline": "outline",
    "team": "Tom Mariano, Jeff Liscouski",
    "images": 0
  },
  {
    "caseId": 39,
    "client": "TransEngen",
    "projectName": "Pharmacy Benefit Verification System",
    "year": 2013,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "HIT",
    "services": "Consulting",
    "projectType": "",
    "engagementType": "Software Development",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "Cloud, Cybersecurity, Service Oriented Architecture, Pharmacy",
    "challenges": "Reduce prescription verification time from 1-3 business days to minutes by automating current process\n\nLooking for full responsibility partner to develop new cloud-based business model\n\nSystem design had to accommodate varied payer results",
    "solution": "Developed secure cloud-based system automating the prescription verification process\n\nCreated virtual hosting strategy with encrypted disks on VMWare and Linux technologies \n\nConfigured a fault tolerant firewall to secure patient data\n\nCollaborated with s",
    "provenResults": "Highly sensitive patient data now secure in cloud-based environment\n\nReduced hosting costs by 70% with new virtual hosting solution\n\nAutomated verification process reduced response time from1-3 business days to ~5 minutes",
    "situation": "Healthcare technology company providing benefit verification services must expedite the prescription approval process while ensuring security of highly sensitive patient data. Current manual verification process takes 1-3 days before  prescription is writ",
    "keywords": "Cloud, cybersecurity, service oriented architecture (SOA), pharmacy",
    "summary": "Foliage was selected to develop a web based platform to be used by Pharmaceutical companies for investigating insurance reimbursements for new drugs.  The system interfaces with > 450 insurance companies to query reimbursement information, and processes t",
    "outline": "outline",
    "team": "Adam Hesse",
    "images": 0
  },
  {
    "caseId": 40,
    "client": "Varian",
    "projectName": "Amorphous Silicon Digital X-Ray Imager",
    "year": "",
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "",
    "projectType": "Hardware",
    "engagementType": "Product Consulting",
    "discipline": "",
    "technologies": "Mixed signal PCB design\nInjection molded and cast part design",
    "keywordLookup": "X-Ray, Product Architecture, Platform Architecture",
    "challenges": "Reduce noise output from existing device amplifiers\n\nScale existing panel design for a new panel format\n\nRequires USB communication functionality compatible with existing board",
    "solution": "Identified low noise circuit design elements from existing product line\n\nDesigned a prototype panel to ensure imaging performance and quality\n\nUsed a platform approach for product architecture to allow maximum configuration flexibility",
    "provenResults": "Reduced noise and improved platform performance\n\nEnhanced imaging quality across the product line\n\nAbility to pursue new OEM business",
    "situation": "Leading manufacturer of oncology systems interested in developing a low cost imaging panel for dental application. Support needed to develop product architecture, conceptual design, and initial fabrication of the product.",
    "keywords": "X-ray, product architecture, platform architecture",
    "summary": "X-ray tube and imager manufacturer developing a low cost imaging panel for dental X-rays - needs help developing product architecture, conceptual design and initial fabrication of product",
    "outline": "outline",
    "team": "",
    "images": 0
  },
  {
    "caseId": 41,
    "client": "Viewray",
    "projectName": "Radiation Therapy Control System",
    "year": 2011,
    "brand": "Foliage",
    "industry": "Medical & Life Sciences",
    "sector": "MedTech",
    "services": "Consulting, Design, Development",
    "projectType": "",
    "engagementType": "Software Development",
    "discipline": "",
    "technologies": "",
    "keywordLookup": "FDA, Cancer, Imaging, 501 (k), Oncology",
    "challenges": "Development effort late and over budget – threatening cancellation of entire program\n\nNeeded assessment of current control system design effort to determine what, if anything, could be saved",
    "solution": "Designed and built new control system including software, programmable logic, printed circuit boards and mechanical enclosures\n\nProvided on-site integration and performance testing support\n\nProvided on-site verification",
    "provenResults": "New radiation therapy control system delivered in time for performance demonstration\n\nAdditional Beta test sites arranged\n\nEnabled the start of 510(k) submission to FDA",
    "situation": "Venture-funded medical device company focused on developing advanced radiation therapy technology struggling with development effort of a combined real-time imaging and radiation therapy system for cancer treatment.",
    "keywords": "imaging, cancer, software, 501(k), FDA, oncology",
    "summary": "Combine real-time imaging and radiation therapy system for cancer treatment. Challenge: The majority of the system was built but the control system was late and over budget threatening the entire program. System assessment, Planning, Development\n2 write-u",
    "outline": "outline",
    "team": "Dan Goldman, Greg Walsh",
    "images": 0
  },
  {
    "caseId": 42,
    "client": "Zygo",
    "projectName": "Lithography Lens Metrology System",
    "year": 2007,
    "brand": "Foliage",
    "industry": "Intelligent Manufacturing Solutions",
    "sector": "Semiconductor Equipment",
    "services": "Development, Test",
    "projectType": "Embedded",
    "engagementType": "Software Development",
    "discipline": "Software, Test",
    "technologies": "",
    "keywordLookup": "Time to Market, Lens Surface, Accuracy, 3D Mapping",
    "challenges": "Conflicting approaches to development across international offices stalling the project \n\nProduct knowledge dispersed across global teams impeding effective communication\n\nHighly customized and undocumented software framework requiring experience with com",
    "solution": "Highly collaborative approach built consensus on development strategy among global teams\n\nDeciphered highly complex algorithms without documentation and implemented changes that improved speed and accuracy\n\nProvided technical leadership on planning, defin",
    "provenResults": "Successful full system test on the first attempt\n\nIdentification and correction of lens distortion down to the sub-nanometer level improved precision specifications by 8X \n\nProduct delivered on-time to meet very aggressive 10-month schedule",
    "situation": "Global supplier of optical metrology instruments must deliver new innovative product to meet customer need under extremely tight time constraints. This new product uses 3D mapping to characterize a lens surface requiring a level of accuracy that had never",
    "keywords": "Time to market, 3D mapping, lens surface, accuracy",
    "summary": "Global supplier of optical metrology instruments must deliver new innovative product to meet customer need under extremely tight time constraints. This new product uses 3D mapping to characterize a lens surface requiring a level of accuracy that had never",
    "outline": "outline",
    "team": "Rick Flanders, Tom Mariano",
    "images": 0
  }
]


// load initial data
module.exports.loadCaseStudies = (callback) => {

  CaseStudies.insertMany(preloadedStudies, function(err) {
    console.log(err)
  });

  // preloadedStudies.forEach(elem => {
  //   CaseStudies.create({
  //     caseId: elem.caseId,
  //     client: elem.client,
  //     projectName: elem.projectName,
  //     year: elem.year,
  //     brand: elem.brand,
  //     industry: elem.industry,
  //     sector: elem.sector,
  //     services: elem.services,
  //     projectType: elem.projectType,
  //     engagementType: elem.engagementType,
  //     discipline: elem.discipline,
  //     technologies: elem.technologies,
  //     keywordLookup: elem.keywordLookup,
  //     challenges: elem.challenges,
  //     solution: elem.solution,
  //     provenResults: elem.provenResults,
  //     situation: elem.situation,
  //     keywords: elem.keywords,
  //     summary: elem.summary,
  //     team: elem.team,
  //     images: elem.images
  //   })
  // })  

  // CaseStudies.create({
  //   caseId: 1,
  //   client: 'Abaxis',
  //   projectName: 'HL7 Interface Development',
  //   year: 2015,
  //   brand: 'Foliage',
  //   industry: 'Medical & Life Sciences',
  //   sector: 'MedTech',
  //   services: 'Development',
  //   projectType: '',
  //   engagementType: 'Software Development',
  //   discipline: 'Software, Test',
  //   technologies: '',
  //   keywordLookup: 'HL7, Class II, EMR',
  //   challenges: 'Current analyzer capable of sending only ASTM data\n\nAdding HL7 data capability to existing analyzer with minimum system changes\n\nSimplifying implementation of HL7 solution for small medical centers with limited IT support\n\nMissing documentation and artifa',
  //   solution: 'Created HL7 plug-in for analyzer that enabled broader connectivity \n\nDesigned and developed a plug-in to enable and simplify installation of HL7 solution \n\nDocumented QMS process to ensure consistency moving forward',
  //   provenResults: 'Enabled analyzer to deliver data in HL7 format\n\nAble to deliver a customized configuration of HL7 solution to small medical center customers \n\nNow have artifacts and documentation that meet requirements for a Class II medical device',
  //   situation: 'Leading diagnostic medical device manufacturer must improve and expand their connectivity strategy for lab equipment. They need a solution to enable their existing blood chemistry analyzers to communicate via HL7 with EMRs/LIMs.',
  //   keywords: 'HL7, Class II, EMR',
  //   summary: 'Leading diagnostic medical device company needed a solution to enable existing devices to send HL7 data to EMRs.',
  //   team: 'Matt Eisedrath, Peter Rudolph',
  //   images: 0
  // }, (err) => {
  //   if (err) console.log(err)
  // })
  // CaseStudies.create({
  //   caseId: 2,
  //   client: 'Abbott Diabetes',
  //   projectName: 'Next Generation Hospital Glucose Meter and Data Management System',
  //   year: '(Pre 2009)',
  //   brand: 'Foliage',
  //   industry: 'Medical & Life Sciences',
  //   sector: 'MedTech',
  //   services: 'Project Management, Requirements Definition, Design, Development, Verification',
  //   projectType: 'Embedded',
  //   engagementType: '',
  //   discipline: '',
  //   technologies: '',
  //   keywordLookup: 'HL7, Class II, EMR, HIS',
  //   challenges: 'Diverse stakeholders accustomed to working in silo fashion (many from an acquired company)\n\nNo internal HL7 or enterprise platform experience\n\nVery tight time-to-market window (12 months)',
  //   solution: 'Provided dedicated team with deep domain and regulated development experience\n\nFull project responsibility: project management, requirements, architecture, design, development, and verification\n\nCollaborated with stakeholders to align technical decisions',
  //   provenResults: 'Class II data management system designed to receive data from a point-of-care device\n\nDesigned and implemented HL7 interfaces for the HIS and EMR enabling connectivity with meter while minimizing labor and data collection procedures\n\nMet aggressive market',
  //   situation: 'A manufacturer of hospital-based diabetes blood glucose monitors and meters needed to make significant updates to their hospital-based meters and develop a new data management system. Company facing an aggressive market window and had limited experience i',
  //   keywords: 'HL7, Class II, HIS, EMR',
  //   summary: 'Manufacturer of hospital-based diabetes blood glucose monitors and glucose meters needed update to hospital-based meters and new data management system. Foliage developed Class II data management system designed to receive data from a point-of-care device',
  //   team: 'Greg Walsh, John Carey',
  //   images: 0
  // }, (err) => {
  //   if (err) console.log(err)
  // })
  // CaseStudies.create({
  //   caseId: 3,
  //   client: 'Abbott Molecular',
  //   projectName: 'Platform Upgrade & Migration',
  //   year: 2015,
  //   brand: 'Foliage',
  //   industry: 'Medical & Life Sciences',
  //   sector: 'HIT',
  //   services: 'Project Management, Development, Test',
  //   projectType: 'Enterprise',
  //   engagementType: 'Software Development',
  //   discipline: 'Software',
  //   technologies: 'Enterprise',
  //   keywordLookup: 'Migration, Code, Platform, Upgrade, Windows XP, Windows 7',
  //   challenges: 'Need to certify that new OS is compatible with all pieces of their software platform\n\nMust maintain same operational efficiency for hundreds of customers while migrating to the new OS\n\nComplex assessment due to the reliance on third party software',
  //   solution: 'Assessment identified high-risk areas for porting and code requiring rewriting\n\nImplementation strategy focused on moving over a million lines of code to new OS\n\nEnsured compatibility of new OS with ~25 third party software applications',
  //   provenResults: 'New OS allows for enhancement to existing product and future models\n\nNew user interface is more flexible and provides additional reporting options\n\nUpgraded verification test suite ensures continued accuracy of results',
  //   situation: 'Provider of diagnostic testing instruments is faced with obsolescence of current operating system (OS). This critical upgrade is necessary to maintain historical support levels \u000band will provide a solid foundation for the development \u000bof future instrument',
  //   keywords: 'Migration, code, platform, upgrade, Windows XP, Windows 7',
  //   summary: 'Windows XP migration to Windows 8.1, creation of Windows 8.1 Embedded Image, Verification testing of the code',
  //   team: 'Dave Widland, Kevin Petriel',
  //   images: 0
  // }, (err) => {
  //   if (err) console.log(err)
  // })
  // CaseStudies.create({
  //   caseId: 4,
  //   client: 'Advantest',
  //   projectName: 'Advanced Analytics for Error Detection During Chip Design',
  //   year: 2016,
  //   brand: 'Foliage',
  //   industry: 'Intelligent Manufacturing Solutions',
  //   sector: 'Semiconductor Equipment',
  //   services: 'Consulting',
  //   projectType: '',
  //   engagementType: 'Product Consulting',
  //   discipline: 'Consulting, Analytics',
  //   technologies: '',
  //   keywordLookup: 'Data Analytics, Semiconductor, ATE, Automated Test Equipment, Chip Design',
  //   challenges: 'Improvement of chip development cycle with semi-automatic evaluation of chip prototypes and structured exploration of test results\n\nInability to detect error patterns and draw conclusions about potential root causes in the preliminary chip design\n\nOptimiz',
  //   solution: 'Refined algorithmic approaches iteratively and implemented proof of concepts \n\nApplied agile development method using Extreme Programming\n\nDesigned and implemented algorithms supporting error detection, error localization, and operation optimization \n\nEva',
  //   provenResults: 'A novel approach to analysis of chip design test results that can detect errors and optimize operations\n\nDemonstrator application for analysis and optimization of chips\n\nClean documentation of results and design decisions\n\nNew application programming inte',
  //   situation: 'A leading semiconductor company is trying to prove that advanced analytics can be used during chip design and development to detect design errors and optimize chip operations to vastly \nshorten the design cycle.',
  //   keywords: 'Data analytics, Semiconductor, ATE, automated test equipment, chip design',
  //   summary: 'A leading semiconductor company is trying to prove that advanced analytics can be used during chip design and development to detect design errors and optimize chip operations to vastly shorten the design cycle.',
  //   team: 'Aamir Chaudhry and Scott Evans\nGerman Analytics Team – Rich Sanford',
  //   images: 0
  // }, (err) => {
  //   if (err) console.log(err)
  // })
  // CaseStudies.create({
  //   caseId: 5,
  //   client: 'AgaMatrix',
  //   projectName: 'Mobile Application for Diabetes Data Management',
  //   year: 2011,
  //   brand: 'Foliage',
  //   industry: 'Medical & Life Sciences',
  //   sector: 'HIT',
  //   services: 'Design, Development',
  //   projectType: 'Embedded, Data',
  //   engagementType: 'Software Development',
  //   discipline: '',
  //   technologies: 'iOS',
  //   keywordLookup: 'iOS, ADA, UI, Software',
  //   challenges: 'Tight time-to-market with software needed in 90-day window\n\nSeveral competitors vying \u000bfor first-to-market position\n\nLack of mobile application development experience and limited resources',
  //   solution: 'Designed and developed fully functional iOS mobile application for new device\n\nIntegrated team worked seamlessly with client to hit 90-day market window\n\nDeveloped UI, core data model, and several critical features to power application',
  //   provenResults: 'Hit market window with new iOS application\n\nApplication launched at ADA meeting and received favorably by diabetes industry\n\nDelivered recommendations to improve client’s internal development process',
  //   situation: 'An early-stage glucometers and data management solutions company struggling to develop an iOS application. They are looking to differentiate in a crowded marketplace with a    single device enabling proactive disease management –    iPhone plug-in meter w',
  //   keywords: 'iOS, ADA, UI, Software',
  //   summary: 'As a development partner Foliage helped to develop an important mobile data management system for diabetics managing this chronic disease.',
  //   team: 'John Carey, Greg Walsh',
  //   images: 0
  // }, (err) => {
  //   if (err) console.log(err)
  // })
  // CaseStudies.create({
  //   caseId: 6,
  //   client: 'Amgen',
  //   projectName: 'Product Design History File and Requirements Remediation',
  //   year: '',
  //   brand: 'Foliage',
  //   industry: 'Medical & Life Sciences',
  //   sector: 'MedTech',
  //   services: 'ESS',
  //   projectType: 'Requirements Remediation',
  //   engagementType: 'Software Development',
  //   discipline: 'EE, EM, Systems Test, Consulting',
  //   technologies: '',
  //   keywordLookup: '62304, Remediation, FDA, Process Gap Assessment',
  //   challenges: 'Understanding the gaps between current practices and best practices relating to IEC 62304 design history files\n\nUndocumented requirements described by comments in code and some design documentation\n\nPerforming and documenting new verification tests to sho',
  //   solution: 'Performed gap analysis between current practices and IEC 62304 best practices\n\nDiscovered and documented requirements from source code and document review\n\nGenerated and documented new verification tests\n\nTraced the tests to requirements and demonstrated',
  //   provenResults: 'Updated all requirements documents within the design history documents to comply with IEC 62304 \n\nFacilitated submission of requirements documentation to the FDA \n\nReported several defects discovered during code inspection \n\nUpdated the verification trace',
  //   situation: 'Due to changes in the regulatory environment, several commercial dermatological laser systems came to be regarded as medical devices. Manufacturer needs to reverse engineer the systems to achieve IEC 62304 compliance.',
  //   keywords: '62304, remediation, FDA process gap assessment',
  //   summary: 'Due to changes in the regulatory environment, several commercial dermatological laser systems came to be regarded as medical devices.  Manufacturer needed to reverse engineer the devices to achieve IEC 62304 compliance.',
  //   team: 'Mark Hersey',
  //   images: 0
  // }, (err) => {
  //   if (err) console.log(err)
  // })
  // CaseStudies.create({
  //   caseId: 7,
  //   client: 'Applied Materials',
  //   projectName: 'Cost Reduction of Etch Tool',
  //   year: '',
  //   brand: 'Foliage',
  //   industry: 'Intelligent Manufacturing Solutions',
  //   sector: 'Semiconductor Equipment',
  //   services: 'ESS',
  //   projectType: 'Value Engineering',
  //   engagementType: 'System Development',
  //   discipline: '',
  //   technologies: 'Finite Element Analysis',
  //   keywordLookup: 'AMAT, Cost Reduction, Etch Tool, AC Box',
  //   challenges: 'Reduce product costs within 6 months to quickly impact bottom line \n\nDocumentation for chamber cooling manifold unavailable as it was owned by the supplier \n\nEnsure changes to the unit do not compromise performance of etch tool\n\nInternal engineering resou',
  //   solution: 'Reverse engineered existing unit and identified high-cost components for replacement or redesign\n\nSelected alternate commercial off-the-shelf components based on cost, functional and material compatibility analysis\n\nPerformed finite element analysis and p',
  //   provenResults: 'Reduced bill of materials cost by 32%\n\nOverall product cost reduced by 40% – double the original target of 20%\n\nCompetitive bidding identified new manufacturing partner and second source option\n\nRedesign and elimination of manufactured parts reduced assem',
  //   situation: 'Global company developing high precision manufacturing equipment for the semiconductor industry must meet corporate goal to reduce product costs by 20%. Chamber cooling manifold identified as individual subcomponent for significant cost reduction.',
  //   keywords: 'AMAT, Cost Reduction, Etch Tool, AC Box',
  //   summary: 'Global company developing high precision manufacturing equipment for the semiconductor industry must meet corporate goal to reduce product costs by 20%. Chamber cooling manifold identified as individual subcomponent for significant cost reduction.',
  //   team: 'Myron Pugh, Lee Plovnick, Chuck Shafer',
  //   images: 0
  // }, (err) => {
  //   if (err) console.log(err)
  // })
}

// ADD case studies
module.exports.addCaseStudy = (study) => {
  return CaseStudies.create(study)
}

// GET case studies
module.exports.getCaseStudies = (callback, limit) => {
  CaseStudies.find().limit(limit).exec().then(callback)
}

// GET case studies by id
module.exports.getCaseStudyById = (id) => {
  return CaseStudies.findById(id)
// return new Promise((resolve, reject) => {
//   CaseStudies.findById(id).exec((err, study) => {
//     if (err) {
//       reject(err)
//     } else {
//       resolve(study)
//     }
//   })
// })
}

// UPDATE case studies
module.exports.updateCaseStudy = (id, study) => {
  var query = {
    _id: id
  }
  var update = {
    caseId: study.caseId,
    client: study.client,
    projectName: study.projectName,
    year: study.year,
    brand: study.brand,
    industry: study.industry,
    sector: study.sector,
    services: study.services,
    projectType: study.projectType,
    engagementType: study.engagementType,
    discipline: study.discipline,
    technologies: study.technologies,
    keywordLookup: study.keywordLookup,
    challenges: study.challenges,
    solution: study.solution,
    keywords: study.keywords,
    summary: study.summary,
    team: study.team,
    images: study.images,
    outline: study.outline
  }
  let options = {
    new: true
  }

  return CaseStudies.findByIdAndUpdate(id, update, options).exec()

  // return new Promise((resolve, reject) => {
  //   CaseStudies.findByIdAndUpdate(id, update).exec((err, study) => {
  //     if (err) {
  //       reject(err)
  //     } else {
  //       resolve(study)
  //     }
  //   })
  // })

// return new Promise((resolve, reject) => {
//     CaseStudies.findOneAndUpdate(query, update, options).exec((err, study) => {
//       if (err) {
//         reject(err)
//       } else {
//         resolve(study)
//       }
//     })
//   }
}

// DELETE case study
module.exports.removeCaseStudy = (id, callback) => {
  var query = {
    _id: id
  }
  return CaseStudies.findByIdAndRemove(query).exec()
}
